### ISSUE TITLE
No me carga el juego :c

### ISSUE THREAD

**Issue by eklypzee** [ringa-tech/juego-python-ia-plataforma#1]
Cuando intento correr el juego con el comando
`python .\app.py`
me sale este error
pygame 2.1.2 (SDL 2.0.18, Python 3.7.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\app.py", line 1, in <module>
    from game import Game
  File "C:\Users\idogo\Downloads\juego-python-ia-plataforma-main\juego-python-ia-plataforma-main\game.py", line 16, in <module>
    import mediapipe as mp
  File "C:\Users\idogo\AppData\Local\Programs\Python\Python37\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "C:\Users\idogo\AppData\Local\Programs\Python\Python37\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed: The specified module could not be found.

Version de python : 3.7.9
SO : Windows 11
Lenovo S5 Yoga

![image](https://user-images.githubusercontent.com/97110626/211172941-c9480b60-19b0-4919-821e-a06feddf00b9.png)

**Comment by ringa-tech** [comment]
Prueba ejecutando este comando"

```
pip install msvc-runtime
```

Y después intentar de nuevo. Si sigue sin funcionarte me avisas

**Comment by eklypzee** [comment]
Brooo Graciass!!!!!!! :DDD
